---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`testhost.commandemy.training`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: message-app
          port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: default
  routes:
    - match: Host(`testhost.commandemy.training`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: message-app
          port: 8080
