apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: k8s.cno-user-<ENV-USER-ID>-i-01.<ENV-ANIMAL>.commandemy.training
    http:
      paths:
      - path: /
        backend:
          serviceName: our-service
          servicePort: 80
