apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-app
spec:
  rules:
    - host: k8s.cno-user-XX-i-02.commandemy.training
      http:
        paths:
          - backend:
              serviceName: flask-app
              servicePort: 80
